[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fantastic-robot"
authors = [
  { name="Kami2" },
]
description = "Test deployment service"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = ['flask']

[project.urls]
"Homepage" = "https://github.com/kami2/fantastic-robot"
